#!/usr/bin/env php
<?php

/**
 * @file
 * Simple runner file that launches the CLI tool.
 *
 * See https://github.com/consolidation/Robo/blob/master/docs/framework.md.
 */

use Consolidation\AnnotatedCommand\CommandFileDiscovery;
use Robo\Robo;

// Support loading composer autoloader if installed as part of dependencies
// or as project.
if (file_exists(__DIR__.'/vendor/autoload.php')) {
  require_once __DIR__.'/vendor/autoload.php';
}
elseif (file_exists(__DIR__.'/../../autoload.php')) {
  require_once __DIR__ . '/../../autoload.php';
}

$discovery = new CommandFileDiscovery();
$discovery->setSearchPattern('*Command.php');
$commandClasses = $discovery->discover(__DIR__ . '/src/Commands', '\drunomics\Phapp\Commands');

$statusCode = Robo::run(
  $_SERVER['argv'],
  $commandClasses,
  'phapp',
  '@package_version@'
);
exit($statusCode);
