#!/usr/bin/env php
<?php

/**
 * @file
 * Simple command class and runner.
 */

use Robo\Robo;

require __DIR__ . '/vendor/autoload.php';

$commandClasses = [ \drunomics\Phapp\Commands\CreateCommand::class ];
$statusCode = Robo::run(
  $_SERVER['argv'],
  $commandClasses,
  'phapp',
  '0.x-dev'
);
exit($statusCode);
