#!/usr/bin/env php
<?php

/**
 * @file
 * Simple runner file that launches the CLI tool.
 *
 * See https://github.com/consolidation/Robo/blob/master/docs/framework.md.
 */

// Support loading composer autoloader if installed as part of dependencies
// or as project.
if (file_exists(__DIR__.'/vendor/autoload.php')) {
  require_once __DIR__.'/vendor/autoload.php';
}
elseif (file_exists(__DIR__.'/../../autoload.php')) {
  require_once __DIR__ . '/../../autoload.php';
}

$application = new \Robo\Application('phapp','@package_version@');
$runner = new \drunomics\Phapp\PhappRunner();
$statusCode = $runner->run(NULL, NULL, $application);

exit($statusCode);
